name: Deploy to Raspberry Pi with screen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Spring Boot on Raspberry Pi using screen
      run: |
        sshpass -p "${{ secrets.RPI_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }} << 'EOF'
          cd /home/${{ secrets.RPI_USER }}/MOUP-Server
          git pull origin main
          ./gradlew build -x test
          screen -S spring-server -X quit || true
          screen -dmS spring-server bash -c 'set -a && source .env && java -jar MOUP_Server.jar --spring.profiles.active=prod > app.log 2>&1'
        EOF
