name: Deploy Moup-Server to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Spring Boot on Raspberry Pi
      run: |
        sshpass -p "${{ secrets.RPI_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }} << 'EOF'
          # Navigate to the project directory
          cd /home/${{ secrets.RPI_USER }}/MOUP-Server
          
          # Pull the latest changes
          git pull origin main
          
          # Build the Spring Boot application, skipping tests
          ./gradlew build -x test
          
          # Kill any existing Spring Boot process
          pkill -f "java -jar MOUP_Server.jar" || true
          
          # Load environment variables from .bashrc and then from .env
          source ~/.bashrc
          set -a && source .env
          
          # Run the Spring Boot application in the background, redirecting output to app.log
          nohup java -jar MOUP_Server.jar --spring.profiles.active=prod > app.log 2>&1 &
        EOF
