name: Deploy to Raspberry Pi with screen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Spring Boot on Raspberry Pi using screen
      run: |
        sshpass -p "${{ secrets.RPI_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }} << 'EOF'
          cd /home/${{ secrets.RPI_USER }}/MOUP-Server
          git pull origin main
          ./gradlew build -x test
          screen -S spring-server -X quit || true
          cd build/libs
          screen -dmS spring-server java -jar MOUP_Server-0.0.1-SNAPSHOT.jar
        EOF
