name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
            - name: SSH deploy to Raspberry Pi Server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.RPI_HOST }}
                  username: ${{ secrets.RPI_USER }}
                  password: ${{ secrets.RPI_PASS }}
                  port: ${{ secrets.RPI_PORT }}
                  script: |                    
                      cd /home/pi/MOUP-Server
                      git pull origin main
                      ./gradlew build -x test
                      pkill -f 'java.*MOUP' || true
                      nohup java -jar build/libs/*.jar > app.log 2>&1 &
