name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
            - name: SSH deploy to Raspberry Pi Server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.RPI_HOST }}
                  username: ${{ secrets.RPI_USER }}
                  password: ${{ secrets.RPI_PASS }}
                  port: ${{ secrets.RPI_PORT }}
                  script: |                    
                      cd pi
                      sudo ./deploy.sh
