name: Manual DB Initialization

on:
  workflow_dispatch:
    inputs:
      insert_dummy_data:
        description: '기본 DB 생성 후 더미 데이터를 추가로 삽입합니다.'
        required: true
        type: boolean
        default: true

jobs:
  manual-db-init:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SQL on server
        run: |
          sshpass -p "${{ secrets.RPI_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }} << 'EOF'
            set -e
            
            echo "Connecting to server..."

            # Make DB connection info at home directory
            echo "Making DB connection info..."
            echo "[client]" > ~/.my.cnf
            echo "user=root" >> ~/.my.cnf
            echo "password=${{ secrets.DATABASE_PASSWORD }}" >> ~/.my.cnf
            chmod 600 ~/.my.cnf

            # Execute SQL DB Schema
            echo "Executing SQL script..."
            cd /home/${{ secrets.RPI_USER }}/MOUP-Server
            mysql moup < src/main/resources/moup.sql

            # (Optional) Execute SQL Dummy Data
            if [[ "${{ github.event.inputs.insert_dummy_data }}" == "true" ]]; then
              echo "Checkbox is checked. Inserting dummy data..."
              mysql moup < src/main/resources/moup_dummy_data.sql
            else
              echo "Checkbox is not checked. Skipping dummy data insertion."
            fi

            # Delete DB connection info
            echo "Deleting DB connection info..."
            rm ~/.my.cnf

            echo "SQL execution complete."
          EOF
